### ISSUE TITLE
错误使用 `checkToken` 中间件，以及近期将弃用 `checkToken` 

### ISSUE THREAD

**Issue by RainEggplant** [eesast/api#342]
我们的代码有的部分写得有问题，请注意 `checkToken` 并不会阻止未登录用户，它仅会将 `req.auth.tokenValid` 置为 `false`. 

由于将开放第三方 token，而 `checkToken` 并不能区分，所以将弃用之。

如果要仅允许已登录用户，请使用 `authenticate([])`.

**Comment by boltma** [comment]
checkToken原本不是为了允许所有用户登录，但检测token中的用户信息来处理逻辑么？

**Comment by robertying** [comment]
> checkToken原本不是为了允许所有用户登录，但检测token中的用户信息来处理逻辑么？

对的，只是为了拿token的有效性，但是可能实践里面会有问题

**Comment by RainEggplant** [comment]
比如那个查询 team，用的是 checkToken, 但是 router 那里并没有做后续的检验。

**Comment by boltma** [comment]
> 比如那个查询 team，用的是 checkToken, 但是 router 那里并没有做后续的检验。

用于做了self和邀请码的逻辑，不过确实前端好像逻辑是要登录了才能查看队伍

**Comment by duskmoon314** [comment]
唔，article的获取中我用了checkToken，后面如果登录了且权限为root和editor才可以获取不公开的文章（不公开应该主要是待审阅的文章，或者有人使用makePrivate变成私人日记）。不登录的话只能返回公开文章。
